Repository wecode-bootcamp-korea/27-1st-branch-backend, pull requests merged in 2021-12, with the labels that each got.

#2 Add: app branch_tags 추가
  branch_tags/__init__.py
  branch_tags/admin.py
  branch_tags/apps.py
  branch_tags/migrations/0001_initial.py
  branch_tags/migrations/__init__.py
  branch_tags/models.py
  branch_tags/tests.py
  branch_tags/views.py
  keywords/migrations/0001_initial.py
  postings/migrations/0001_initial.py
  postings/models.py
  teambranch/settings.py
  users/migrations/0001_initial.py
  users/models.py
Labels: Status: 리뷰 요청

#3 fix: branch_tags 디렉토리 apps.py tagsconfig name 수정, migrations적용
  branch_tags/apps.py
  branch_tags/migrations/0001_initial.py
  keywords/migrations/0001_initial.py
  postings/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#7 Modified : subscribe=>null=True
  users/migrations/0002_alter_user_subscribe.py
  users/models.py
Labels: Status: 리뷰 요청

#8 add: DB업로더 파일
  .gitignore
  db_uploader.py
Labels: Status: 리뷰 요청

#11 modify: models.py
  branch_tags/migrations/0002_auto_20211202_0625.py
  branch_tags/migrations/0003_auto_20211202_0652.py
  branch_tags/migrations/0004_auto_20211202_0757.py
  branch_tags/models.py
Labels: Status: Accepted

#10 add: 로그인 기능구현
  users/urls.py
  users/views.py
Labels: Status: Accepted

#14 add: models.py 수정, core 디렉토리, TimeStampModel 추가
  branch_tags/migrations/0005_auto_20211202_1159.py
  branch_tags/models.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  keywords/migrations/0002_auto_20211202_1159.py
  keywords/models.py
  postings/migrations/0002_auto_20211202_1159.py
  postings/models.py
  teambranch/settings.py
  users/migrations/0003_auto_20211202_1159.py
  users/models.py
Labels: Status: 리뷰 요청

#15 add: 로그인 데코레이터 기능 구현
  core/utils.py
  users/models.py
  users/views.py
Labels: Status: Accepted

#16 add : 유저 태그 리스트 구현
  branch_tags/urls.py
  branch_tags/views.py
  teambranch/urls.py
  users/urls.py
Labels: Status: 리뷰 요청

#12 add: 마이페이지 유저정보 불러오기 기능 구현
  postings/views.py
  users/urls.py
  users/validation.py
  users/views.py
Labels: Status: 리뷰 요청

#22 modify: postings models.py 수정
  db_uploader.py
  fakerdata.py
  postings/migrations/0003_auto_20211206_0543.py
  postings/migrations/0004_auto_20211206_1200.py
  postings/migrations/0005_auto_20211206_1227.py
  postings/models.py
Labels: Status: 리뷰 요청

#19 add: 포스트 리스트 구현
  postings/urls.py
  postings/views.py
  teambranch/urls.py
  users/validation.py
  users/views.py
Labels: Status: 리뷰 요청

#17 modify : 유저 리스트
  branch_tags/views.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#21 add : 키워드 리스트 구현
  keywords/urls.py
  keywords/views.py
  teambranch/urls.py
Labels: Status: 리뷰 요청

#18 add: PostView
  postings/migrations/0001_initial.py
  postings/migrations/0002_auto_20211202_1159.py
  postings/urls.py
  postings/views.py
Labels: Status: 리뷰 요청

#23 modify: manytomany through model추가, migrations 초기화
  branch_tags/migrations/0001_initial.py
  branch_tags/migrations/0002_auto_20211202_0625.py
  branch_tags/migrations/0003_auto_20211202_0652.py
  branch_tags/migrations/0004_auto_20211202_0757.py
  branch_tags/migrations/0005_auto_20211202_1159.py
  branch_tags/models.py
  db_uploader.py
  keywords/migrations/0001_initial.py
  keywords/migrations/0002_auto_20211202_1159.py
  postings/migrations/0001_initial.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_subscribe.py
  users/migrations/0003_auto_20211202_1159.py
Labels: Status: Accepted

#25 modify: migrations 초기화
  branch_tags/migrations/0001_initial.py
  fakerdata.py
  keywords/migrations/0001_initial.py
  postings/migrations/0001_initial.py
  postings/migrations/0002_auto_20211202_1159.py
  postings/migrations/0003_auto_20211206_0543.py
  postings/migrations/0004_auto_20211206_1200.py
  postings/migrations/0005_auto_20211206_1227.py
  users/migrations/0001_initial.py
Labels: Status: Accepted

#24 modify: post_name->posting_name, add: prev/next_posting
  postings/urls.py
  postings/views.py
Labels: Status: 수정 요청

#27 modify : migration 정션테이블
  branch_tags/migrations/0002_alter_usersusertags_unique_together.py
  branch_tags/migrations/0003_alter_postingspostingtags_unique_together.py
  branch_tags/models.py
Labels: Status: Accepted

#28 modify : 유저테이블 변경
  users/migrations/0002_auto_20211208_0602.py
  users/migrations/0003_subscribe_unique_subscribing_subscriber.py
  users/models.py
Labels: Status: 리뷰 요청

#29 modify : 태그모델 수정
  branch_tags/migrations/0002_alter_usersusertags_unique_together.py
  branch_tags/migrations/0002_auto_20211208_0652.py
  branch_tags/migrations/0003_alter_postingspostingtags_unique_together.py
  branch_tags/models.py
Labels: Status: 리뷰 요청

#26 modify : 유저 태그 리스트 정렬 및 limit, offset
  branch_tags/views.py
Labels: Status: 리뷰 요청

#33 modify : 유저 리스트
  users/views.py
Labels: Status: 리뷰 요청

#31 add: 마이페이지 프로필 보기 기능 구현
  postings/urls.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#30 modify : 포스팅 리스트 기능 추가
  postings/urls.py
  postings/views.py
Labels: Status: Accepted

#32 add: 포스트 좋아요 기능구현
  db_uploader.py
  postings/urls.py
  postings/views.py
Labels: Status: Accepted

#36 modify : 모든 뷰에 ID컬럼 추가
  postings/views.py
  users/views.py
Labels: Status: Accepted

#34 add: 포스트 댓글 기능 구현
  core/utils.py
  postings/models.py
  postings/urls.py
  postings/views.py
  teambranch/urls.py
Labels: Status: 리뷰 요청

#38 Final Add : 구독하기 기능
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청
